### ISSUE TITLE
Include "p3.2xlarge" GPU instance during CI

### ISSUE THREAD

**Issue by ashishkamra** [openshift-psap/ci-artifacts#181]
Include the "p3.2xlarge" GPU instance as well during CI along with the cheaper "g4dn.xlarge"

When we onboard performance tests in the CI, we should run the training workloads on the p3 instance and the inference workloads in the g4dn instance

**Comment by kpouget** [comment]
ack,
for the record, the switch of instance will be easy to setup with @omertuc's rewrite of the `set_scale.sh` script:
```
toolbox/cluster/set_scale.sh g4dn.xlarge 0
toolbox/cluster/set_scale.sh p3.2xlarge 1
toolbox/gpu-operator/wait_deployment.sh
```
