### ISSUE TITLE
Create a full weekly suite for the PSAP operators suite

### ISSUE THREAD

**Issue by ArangoGutierrez** [openshift-psap/ci-artifacts#206]
We should have a BIG test that runs weekly, with chaos testing and other best test practices paths 

the idea would be to: 

- run the basic installs, let it run for a couple of minutes
- run a very small ML perf benchmark
- run a chaos run, randomly deleting components from the operators and monitoring if the operators recover from it
- run a scale up and scale down test (GPU and NFD test) 
- run a cluster upgrade

This will test and stress PSAP operators to common real world scenarios so we can be prepared

**Comment by chaitanyaenr** [comment]
Hi @ArangoGutierrez, we have been working on a tool for chaos testing various components of Kubernetes/OpenShift - https://github.com/cloud-bulldozer/kraken. Is this something that can help with testing the resiliency of the PSAP operators?

**Comment by ArangoGutierrez** [comment]
sure, let's sync up and create some action items!
