### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ArangoGutierrez** [openshift-psap/ci-artifacts#82]
Update README 
and Also write proper documentation about the available playbooks

**Comment by ArangoGutierrez** [comment]
I am going to check how can we use Prow to get pages like we do for NFD https://kubernetes-sigs.github.io/node-feature-discovery/stable/get-started/index.html

**Comment by kpouget** [comment]
I'm not sure what would be the link with Prow, but I like the idea to have a proper documentation website

I like `Sphinx` + `readthedoc` template, but I'm open to other engines :)

**Comment by kpouget** [comment]
I shared the PR of first version of the documentation https://github.com/openshift-psap/ci-artifacts/pull/131
It's online at this address: https://openshift-psap.github.io/ci-artifacts/
