### ISSUE TITLE
Implement some unit testing for toolbox scripts

### ISSUE THREAD

**Issue by kpouget** [openshift-psap/ci-artifacts#92]
The `toolbox` scripts are used to test the deployment of the GPU operator, so most of their code (ansible playbooks and roles) is tested before merging a new PR in the `master` branch (`\test gpu-operator-e2e`) and in the nightly testing:

![image](https://user-images.githubusercontent.com/7559202/111439852-0ea24080-8706-11eb-9368-d7bd1dde5b76.png)

But the GPU operator doesn't cover 100% of the `toolbox` features, and some flags and code branches might be left untested. This is for instance what happened with `toolbox/entitlement/test.sh` that got broken when no flag was passed (see the fix in https://github.com/openshift-psap/ci-artifacts/commit/cf8a276548bf4da3d2712b2b4cee99793da85884), which isn't executed in the GPU Operator testing.

This ticket will track the progress of the design and development of unit tests.

**Comment by ArangoGutierrez** [comment]
https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html 

> Validating tasks: check mode and diff mode
Ansible provides two modes of execution that validate tasks: check mode and diff mode. These modes can be used separately or together. They are useful when you are creating or editing a playbook or role and you want to know what it will do. In check mode, Ansible runs without making any changes on remote systems. Modules that support check mode report the changes they would have made. Modules that do not support check mode report nothing and do nothing. In diff mode, Ansible provides before-and-after comparisons. Modules that support diff mode display detailed information. You can combine check mode and diff mode for detailed validation of your playbook or role.

**Comment by kpouget** [comment]
I had a look at the `check mode` but it's working badly when things like `register: task` and `task.stdout` are used, that is, everywhere in our playbooks :(
