### ISSUE TITLE
Measure the code coverage of the presubmit tests

### ISSUE THREAD

**Issue by kpouget** [openshift-psap/ci-artifacts#93]
In parallel of implementing unit testing (#92), it would be interesting to measure the code coverage of the GPU Operator testing + Unit testing, to ensure that all the playbook tasks are executed at least once as part of the presubmit testing.

This ticket will track the design and development of this task.

**Comment by ArangoGutierrez** [comment]
I don't get this idea, could you provide more detail

Code coverage like to the playbooks/roles ? or to check how the ci-artifacts are testing every part of the GPU operator test, I am a bit confused

**Comment by kpouget** [comment]
> Code coverage like to the playbooks/roles 

yes, code coverage of the ansible role tasks (that's linked the unit testing #92), to make sure that during the presubmit test, we run each task at least once. 
The idea is that by running it at least once, you catch typos and other silly mistakes like undefined variables, etc
So with a code coverage of 100% during the test, you know (for sure, hopefully) that 1/ there is no undefined variables (with `bash -e` for scripts and ansible does it by default), 2/ there is no dead branch (eg: `if var == "yess"`), etc
